drop trigger TIB_ERREUR_CAISSE
/

drop trigger TIB_MOTIF_REGULARISATION
/

alter table AGENT
   drop constraint FK_AGENT_DEPENDRE_AGENCE
/

alter table AGENT
   drop constraint FK_AGENT_ETRE_TYPE_AGE
/

alter table ERREURS_CAISSES_REGUL
   drop constraint FK_ERREURS__AVOIR_TYPE_REG
/

alter table ERREURS_CAISSES_REGUL
   drop constraint FK_ERREURS__AVOIR3_MOTIF_RE
/

alter table ERREURS_CAISSES_REGUL
   drop constraint FK_ERREURS__CORRESPON_ERREUR_C
/

alter table ERREURS_CAISSES_REGUL
   drop constraint FK_ERREURS__SAISIR_AGENT
/

alter table ERREUR_CAISSE
   drop constraint FK_ERREUR_C_AVOIR2_TYPE_ERR
/

alter table ERREUR_CAISSE
   drop constraint FK_ERREUR_C_COMMETRE_AGENT
/

alter table ERREUR_CAISSE
   drop constraint FK_ERREUR_C_ETRE_VICT_AGENCE
/

alter table ERREUR_CAISSE
   drop constraint FK_ERREUR_C_RELATION__STATUS_R
/

drop table AGENCE cascade constraints
/

drop index ETRE_FK
/

drop table AGENT cascade constraints
/

drop index SAISIR_FK
/

drop index AVOIR_FK
/

drop index CORRESPONDRE_FK
/

drop table ERREURS_CAISSES_REGUL cascade constraints
/

drop index AVOIR2_FK
/

drop index RELATION_5_FK
/

drop index ETRE_VICTIME_FK
/

drop index COMMETRE_FK
/

drop table ERREUR_CAISSE cascade constraints
/

drop table MOTIF_REGULARISATION cascade constraints
/

drop table STATUS_REGULARISATION cascade constraints
/

drop table TYPE_AGENT cascade constraints
/

drop table TYPE_ERREUR cascade constraints
/

drop table TYPE_REGULARISATION cascade constraints
/

drop sequence AUTO_INCREMENTATION
/

create sequence AUTO_INCREMENTATION
increment by 1
start with 0
 minvalue 0
/

CREATE TABLE  "MOTIF_REGULARISATION" 
   (	"CODE_MOTIF_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRIPTION_MOTIF_REGUL" VARCHAR2(1024) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_MOTIF_REGULA_MOTIF_RE" CHECK (CODE_MOTIF_REGULARISATION >= 0) ENABLE, 
	 CONSTRAINT "CKC_DESCRIPTION_MOTIF_MOTIF_RE" CHECK (DESCRIPTION_MOTIF_REGUL = upper(DESCRIPTION_MOTIF_REGUL)) ENABLE, 
	 CONSTRAINT "PK_MOTIF_REGULARISATION" PRIMARY KEY ("CODE_MOTIF_REGULARISATION") ENABLE
   )
/

CREATE TABLE  "STATUS_REGULARISATION" 
   (	"CODE_STATUT_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_STATUS_REGULARISATION" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_STATUT_REGUL_STATUS_R" CHECK (CODE_STATUT_REGULARISATION in (0,1,2)) ENABLE, 
	 CONSTRAINT "CKC_NOM_STATUS_REGULA_STATUS_R" CHECK (NOM_STATUS_REGULARISATION = upper(NOM_STATUS_REGULARISATION)) ENABLE, 
	 CONSTRAINT "PK_STATUS_REGULARISATION" PRIMARY KEY ("CODE_STATUT_REGULARISATION") ENABLE
   )
/

   CREATE TABLE  "TYPE_AGENT" 
   (	"CODE_TYPE_AGENT" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_TYPE_AGENT" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_AGENT_TYPE_AGE" CHECK (CODE_TYPE_AGENT in (0,1,2)) ENABLE, 
	 CONSTRAINT "CKC_NOM_TYPE_AGENT_TYPE_AGE" CHECK (NOM_TYPE_AGENT = upper(NOM_TYPE_AGENT)) ENABLE, 
	 CONSTRAINT "PK_TYPE_AGENT" PRIMARY KEY ("CODE_TYPE_AGENT") ENABLE
   )
/
   
   CREATE TABLE  "TYPE_ERREUR" 
   (	"CODE_TYPE_ERREUR" CHAR(1) NOT NULL ENABLE, 
	"NOM_TYPE_ERREUR" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_ERREUR_TYPE_ERR" CHECK (CODE_TYPE_ERREUR in ('E','D') and CODE_TYPE_ERREUR = upper(CODE_TYPE_ERREUR)) ENABLE, 
	 CONSTRAINT "CKC_NOM_TYPE_ERREUR_TYPE_ERR" CHECK (NOM_TYPE_ERREUR = upper(NOM_TYPE_ERREUR)) ENABLE, 
	 CONSTRAINT "PK_TYPE_ERREUR" PRIMARY KEY ("CODE_TYPE_ERREUR") ENABLE
   )
/

   CREATE TABLE  "TYPE_REGULARISATION" 
   (	"CODE_TYPE_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_TYPE_REGULARISATION" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_REGULAR_TYPE_REG" CHECK (CODE_TYPE_REGULARISATION in (0,1)) ENABLE, 
	 CONSTRAINT "CKC_NOM_TYPE_REGULARI_TYPE_REG" CHECK (NOM_TYPE_REGULARISATION = upper(NOM_TYPE_REGULARISATION)) ENABLE, 
	 CONSTRAINT "PK_TYPE_REGULARISATION" PRIMARY KEY ("CODE_TYPE_REGULARISATION") ENABLE
   )
/
   
   CREATE TABLE  "AGENCE" 
   (	"CODE_AGENCE" VARCHAR2(32) NOT NULL ENABLE, 
	"NOM_AGENCE" VARCHAR2(256) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_AGENCE_AGENCE" CHECK (CODE_AGENCE = upper(CODE_AGENCE)) ENABLE, 
	 CONSTRAINT "CKC_NOM_AGENCE_AGENCE" CHECK (NOM_AGENCE = upper(NOM_AGENCE)) ENABLE, 
	 CONSTRAINT "PK_AGENCE" PRIMARY KEY ("CODE_AGENCE") ENABLE
   )
/
   
   CREATE TABLE  "AGENT" 
   (	"CODE_AGENT" VARCHAR2(32) NOT NULL ENABLE, 
	"CODE_AGENCE" VARCHAR2(32), 
	"CODE_TYPE_AGENT" NUMBER(*,0) NOT NULL ENABLE, 
	"MAIL" VARCHAR2(320), 
	"MOT_DE_PASSE" VARCHAR2(32), 
	"NOM" VARCHAR2(32), 
	"PRENOM" VARCHAR2(32), 
	 CONSTRAINT "CKC_CODE_AGENT_AGENT" CHECK (CODE_AGENT = upper(CODE_AGENT)) ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_AGENT_AGENT" CHECK (CODE_TYPE_AGENT in (0,1,2)) ENABLE, 
	 CONSTRAINT "CKC_MAIL_AGENT" CHECK (MAIL is null or (MAIL = lower(MAIL))) ENABLE, 
	 CONSTRAINT "CKC_NOM_AGENT" CHECK (NOM is null or (NOM = upper(NOM))) ENABLE, 
	 CONSTRAINT "CKC_PRENOM_AGENT" CHECK (PRENOM is null or (PRENOM = upper(PRENOM))) ENABLE, 
	 CONSTRAINT "PK_AGENT" PRIMARY KEY ("CODE_AGENT") ENABLE
   )
/
   
   ALTER TABLE  "AGENT" ADD CONSTRAINT "FK_AGENT_DEPENDRE_AGENCE" FOREIGN KEY ("CODE_AGENCE")
	  REFERENCES  "AGENCE" ("CODE_AGENCE") ENABLE
/
ALTER TABLE  "AGENT" ADD CONSTRAINT "FK_AGENT_ETRE_TYPE_AGE" FOREIGN KEY ("CODE_TYPE_AGENT")
	  REFERENCES  "TYPE_AGENT" ("CODE_TYPE_AGENT") ENABLE
/


CREATE INDEX  "ETRE_FK" ON  "AGENT" ("CODE_TYPE_AGENT") 
  ;
  
  CREATE TABLE  "ERREUR_CAISSE" 
   (	"ERREUR_CAISSE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CODE_AGENT" VARCHAR2(32) NOT NULL ENABLE, 
	"CODE_TYPE_ERREUR" CHAR(1) NOT NULL ENABLE, 
	"CODE_AGENCE" VARCHAR2(32) NOT NULL ENABLE, 
	"CODE_STATUT_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"DATE_VACATION" DATE NOT NULL ENABLE, 
	"MONTANT" NUMBER(19,2) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_AGENT_ERREUR_C" CHECK (CODE_AGENT = upper(CODE_AGENT)) ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_ERREUR_ERREUR_C" CHECK (CODE_TYPE_ERREUR in ('E','D') and CODE_TYPE_ERREUR = upper(CODE_TYPE_ERREUR)) ENABLE, 
	 CONSTRAINT "CKC_CODE_AGENCE_ERREUR_C" CHECK (CODE_AGENCE = upper(CODE_AGENCE)) ENABLE, 
	 CONSTRAINT "CKC_CODE_STATUT_REGUL_ERREUR_C" CHECK (CODE_STATUT_REGULARISATION in (0,1,2)) ENABLE, 
	 CONSTRAINT "PK_ERREUR_CAISSE" PRIMARY KEY ("ERREUR_CAISSE_ID") ENABLE
   )
/

ALTER TABLE  "ERREUR_CAISSE" ADD CONSTRAINT "FK_ERREUR_C_AVOIR2_TYPE_ERR" FOREIGN KEY ("CODE_TYPE_ERREUR")
	  REFERENCES  "TYPE_ERREUR" ("CODE_TYPE_ERREUR") ENABLE
/
ALTER TABLE  "ERREUR_CAISSE" ADD CONSTRAINT "FK_ERREUR_C_COMMETRE_AGENT" FOREIGN KEY ("CODE_AGENT")
	  REFERENCES  "AGENT" ("CODE_AGENT") ENABLE
/
ALTER TABLE  "ERREUR_CAISSE" ADD CONSTRAINT "FK_ERREUR_C_ETRE_VICT_AGENCE" FOREIGN KEY ("CODE_AGENCE")
	  REFERENCES  "AGENCE" ("CODE_AGENCE") ENABLE
/
ALTER TABLE  "ERREUR_CAISSE" ADD CONSTRAINT "FK_ERREUR_C_RELATION__STATUS_R" FOREIGN KEY ("CODE_STATUT_REGULARISATION")
	  REFERENCES  "STATUS_REGULARISATION" ("CODE_STATUT_REGULARISATION") ENABLE
/


CREATE INDEX  "AVOIR2_FK" ON  "ERREUR_CAISSE" ("CODE_TYPE_ERREUR") 
  ;

CREATE INDEX  "COMMETRE_FK" ON  "ERREUR_CAISSE" ("CODE_AGENT") 
  ;

CREATE INDEX  "ETRE_VICTIME_FK" ON  "ERREUR_CAISSE" ("CODE_AGENCE") 
  ;

CREATE INDEX  "RELATION_5_FK" ON  "ERREUR_CAISSE" ("CODE_STATUT_REGULARISATION") 
  ;

CREATE TABLE  "ERREURS_CAISSES_REGUL" 
   (	"DTIME_REGULARISATION" TIMESTAMP (6) NOT NULL ENABLE, 
	"CODE_AGENT" VARCHAR2(32) NOT NULL ENABLE, 
	"CODE_MOTIF_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"ERREUR_CAISSE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CODE_TYPE_REGULARISATION" NUMBER(*,0) NOT NULL ENABLE, 
	"MONTANT_REGULARISATION" NUMBER(19,2) NOT NULL ENABLE, 
	 CONSTRAINT "CKC_CODE_AGENT_ERREURS_" CHECK (CODE_AGENT = upper(CODE_AGENT)) ENABLE, 
	 CONSTRAINT "CKC_CODE_TYPE_REGULAR_ERREURS_" CHECK (CODE_TYPE_REGULARISATION in (0,1)) ENABLE, 
	 CONSTRAINT "PK_ERREURS_CAISSES_REGUL" PRIMARY KEY ("DTIME_REGULARISATION") ENABLE
   )
/
   
   ALTER TABLE  "ERREURS_CAISSES_REGUL" ADD CONSTRAINT "FK_ERREURS__AVOIR3_MOTIF_RE" FOREIGN KEY ("CODE_MOTIF_REGULARISATION")
	  REFERENCES  "MOTIF_REGULARISATION" ("CODE_MOTIF_REGULARISATION") ENABLE
/
ALTER TABLE  "ERREURS_CAISSES_REGUL" ADD CONSTRAINT "FK_ERREURS__AVOIR_TYPE_REG" FOREIGN KEY ("CODE_TYPE_REGULARISATION")
	  REFERENCES  "TYPE_REGULARISATION" ("CODE_TYPE_REGULARISATION") ENABLE
/
ALTER TABLE  "ERREURS_CAISSES_REGUL" ADD CONSTRAINT "FK_ERREURS__CORRESPON_ERREUR_C" FOREIGN KEY ("ERREUR_CAISSE_ID")
	  REFERENCES  "ERREUR_CAISSE" ("ERREUR_CAISSE_ID") ENABLE
/
ALTER TABLE  "ERREURS_CAISSES_REGUL" ADD CONSTRAINT "FK_ERREURS__SAISIR_AGENT" FOREIGN KEY ("CODE_AGENT")
	  REFERENCES  "AGENT" ("CODE_AGENT") ENABLE
/


CREATE INDEX  "AVOIR_FK" ON  "ERREURS_CAISSES_REGUL" ("CODE_TYPE_REGULARISATION") 
  ;

CREATE INDEX  "CORRESPONDRE_FK" ON  "ERREURS_CAISSES_REGUL" ("ERREUR_CAISSE_ID") 
  ;

CREATE INDEX  "SAISIR_FK" ON  "ERREURS_CAISSES_REGUL" ("CODE_AGENT") 
  ;
  
  create or replace trigger TIB_ERREUR_CAISSE before insert
on ERREUR_CAISSE for each row
declare
    integrity_error  exception;
    errno            integer;
    errmsg           char(200);
    dummy            integer;
    found            boolean;

begin
    --  La colonne "ERREUR_CAISSE_ID" utilise la sequence AUTO_INCREMENTATION
    select AUTO_INCREMENTATION.NEXTVAL INTO :new.ERREUR_CAISSE_ID from dual;

--  Traitement d'erreurs
exception
    when integrity_error then
       raise_application_error(errno, errmsg);
end;
/


create or replace trigger TIB_MOTIF_REGULARISATION before insert
on MOTIF_REGULARISATION for each row
declare
    integrity_error  exception;
    errno            integer;
    errmsg           char(200);
    dummy            integer;
    found            boolean;

begin
    --  La colonne "CODE_MOTIF_REGULARISATION" utilise la sequence AUTO_INCREMENTATION
    select AUTO_INCREMENTATION.NEXTVAL INTO :new.CODE_MOTIF_REGULARISATION from dual;

--  Traitement d'erreurs
exception
    when integrity_error then
       raise_application_error(errno, errmsg);
end;
/
ALTER TRIGGER  "TIB_MOTIF_REGULARISATION" ENABLE
/

ALTER TRIGGER  "TIB_ERREUR_CAISSE" ENABLE
/
